# Generated by Django 6.1.1 on 2026-10-02 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Khách hàng'), ('admin', 'Admin'), ('cashier', 'Thu ngân'), ('chef', 'Bếp'), ('staff', 'Phục vụ')], default='customer', max_length=20),
        ),
    ]
