# Generated by Django 6.1 on 2026-09-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(max_length=10)),
                ('request_type', models.CharField(choices=[('ice', 'Thêm đá'), ('towel', 'Khăn lạnh'), ('chopsticks', 'Đổi đũa'), ('payment', 'Gọi tính tiền'), ('other', 'Khác')], max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_handled', models.BooleanField(default=False)),
            ],
        ),
    ]
